export const icons = {
  "arrow-right": "/icons/arrow-right.svg",
  arrow: "/icons/arrow.svg",
  battery: "/icons/battery.svg",
  bell: "/icons/bell.svg",
  brain: "/icons/brain.svg",
  "circle-dashed": "/icons/circle-dashed.svg",
  community: "/icons/community.svg",
  "flower-lotus-duotone": "/icons/flower-lotus-duotone.svg",
  "flower-lotus": "/icons/flower-lotus.svg",
  "food-apple": "/icons/food-apple.svg",
  heart: "/icons/heart.svg",
  heartbeat: "/icons/heartbeat.svg",
  hearts: "/icons/hearts.svg",
  "leaf-fill": "/icons/leaf-fill.svg",
  leaf: "/icons/leaf.svg",
  "moon-sleep": "/icons/moon-sleep.svg",
  oxygen: "/icons/oxygen.svg",
  "person-arms-up": "/icons/person-arms-up.svg",
  "person-run": "/icons/person-run.svg",
  play: "/icons/play.svg",
  "power-sleep": "/icons/power-sleep.svg",
  premium: "/icons/premium.svg",
  running: "/icons/running.svg",
  scanner: "/icons/scanner.svg",
  "shield-check": "/icons/shield-check.svg",
  star: "/icons/star.svg",
  stress: "/icons/stress.svg",
  "sun-high": "/icons/sun-high.svg",
  sunrise: "/icons/sunrise.svg",
  "user-rounded": "/icons/user-rounded.svg",
  waterdrop: "/icons/waterdrop.svg",
  "wave-saw": "/icons/wave-saw.svg",
  wave: "/icons/wave.svg",
  yoga: "/icons/yoga.svg",
} as const;

export type IconName = keyof typeof icons;
